INSERT INTO ALIMENTOS (NOMBRE, CATEGORIA, FECHA_VENCIMIENTO, STOCK, OBSERVACIONES) VALUES ('Arroz', 'Cereal', DATE '2026-05-01', 100, 'Paquete 1kg');
INSERT INTO ALIMENTOS (NOMBRE, CATEGORIA, FECHA_VENCIMIENTO, STOCK, OBSERVACIONES) VALUES ('Leche', 'Lácteo', DATE '2025-12-15', 50, 'UHT 1L');

INSERT INTO MEDICAMENTOS (NOMBRE, PRINCIPIO_ACTIVO, DOSIS, FECHA_VENCIMIENTO, STOCK, OBSERVACIONES) VALUES ('Paracetamol', 'Paracetamol', '500 mg', DATE '2026-02-01', 200, 'Tabletas');
INSERT INTO MEDICAMENTOS (NOMBRE, PRINCIPIO_ACTIVO, DOSIS, FECHA_VENCIMIENTO, STOCK, OBSERVACIONES) VALUES ('Ibuprofeno', 'Ibuprofeno', '400 mg', DATE '2025-11-30', 120, 'Tabletas');
COMMIT;