CREATE TABLE ALIMENTOS (
                           ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           NOMBRE VARCHAR2(200) NOT NULL,
                           CATEGORIA VARCHAR2(100),
                           FECHA_VENCIMIENTO DATE,
                           STOCK NUMBER(10),
                           OBSERVACIONES VARCHAR2(4000)
);

CREATE TABLE MEDICAMENTOS (
                              ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              NOMBRE VARCHAR2(200) NOT NULL,
                              PRINCIPIO_ACTIVO VARCHAR2(200),
                              DOSIS VARCHAR2(100),
                              FECHA_VENCIMIENTO DATE,
                              STOCK NUMBER(10),
                              OBSERVACIONES VARCHAR2(4000)
);

-- Usuario y permisos (ejecutar como DBA si es necesario)
-- CREATE USER app_user IDENTIFIED BY strong_password;
-- GRANT CONNECT, RESOURCE TO app_user;
-- GRANT CREATE SEQUENCE, CREATE TABLE TO app_user;

COMMIT;